apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from .views import *
from apps.hr import views


app_name = "home"
urlpatterns = [

    # The home page
    path('', index, name='home'),
    path('old/', index_old, name='home_old'),
    #path('toooest333/', testN, name='st2'),


    # Matches any html file
    re_path(r'^.*\.*', pages, name='pages'),

]

apps/hr/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from .views import *
from apps.home import views


app_name = "hr"
urlpatterns = [

    # The home page
    # path('', views.hrIndex, name='home'),
    path('', dashboard, name='dahsboard'),
    path('allEmp/', EmpView.as_view(), name='emplist'),
    path('teacher/<slug:slug>', TeacherDetailView.as_view(), name='teacher-detail'),
    path('staff/<slug:slug>', StaffDetailView.as_view(), name='staff-detail'),
    path('toooest/', views.index_old, name='st'),
    path('conf/', configView, name='confiHR'),

    # Matches any html file
    #re_path(r'^.*\.*', views.pages, name='pages'),

]

apps/library/urls.py
from django.urls import path
from .views import *


app_name = "library"


urlpatterns = [
    path('', allbooks, name='library_home'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    # Auth routes - login / register
    path("", include("apps.authentication.urls")),

    # ADD NEW Routes HERE

    path("hr", include("apps.hr.urls")),
    path("library", include("apps.library.urls")),
    path("admission/", include("apps.admission.urls")),

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls")),

]

apps/templates/includes/navigation.html
<!-- [ Header ] start -->
<header class="navbar pcoded-header navbar-expand-lg navbar-light">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
        <a href="/" class="b-brand">
            <div class="b-bg">
                <i class="feather icon-trending-up"></i>
            </div>
            <span class="b-title">Datta Able</span>
        </a>
    </div>
    <a class="mobile-menu" id="mobile-header" href="javascript:">
        <i class="feather icon-more-horizontal"></i>
    </a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
                    class="feather icon-maximize"></i></a></li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">Dropdown</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="javascript:">Action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Another action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Something else here</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <div class="main-search">
                    <div class="input-group">
                        <input type="text" id="m-search" class="form-control" placeholder="Search . . .">
                        <a href="javascript:" class="input-group-append search-close">
                            <i class="feather icon-x input-group-text"></i>
                        </a>
                        <span class="input-group-append search-btn btn btn-primary">
                                <i class="feather icon-search input-group-text"></i>
                            </span>
                    </div>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li>
                <label>
                    <i class="icon feather icon-sun" id="theme-indicator"></i>
                    <input type="checkbox" id="theme-switch" class="d-none">
                </label>
            </li>
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"><i
                            class="icon feather icon-bell"></i></a>
                    <div class="dropdown-menu dropdown-menu-right notification">
                        <div class="noti-head">
                            <h6 class="d-inline-block m-b-0">Notifications</h6>
                            <div class="float-right">
                                <a href="javascript:" class="m-r-10">mark as read</a>
                                <a href="javascript:">clear all</a>
                            </div>
                        </div>
                        <ul class="noti-body">
                            <li class="n-title">
                                <p class="m-b-0">NEW</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-1.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>John Doe</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>New ticket Added</p>
                                    </div>
                                </div>
                            </li>
                            <li class="n-title">
                                <p class="m-b-0">EARLIER</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-2.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Joseph William</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>Prchace New Theme and make payment</p>
                                    </div>
                                </div>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-3.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>currently login</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <div class="noti-footer">
                            <a href="javascript:">show all</a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="dropdown drp-user">
                    <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon feather icon-settings"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-notification">
                        <div class="pro-head">
                            <img src="{{ ASSETS_ROOT }}/images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image">
                            <span>
                                {{ request.user.username }}    
                            </span>
                            <a href="/auth-signin.html" class="dud-logout" title="Logout">
                                <i class="feather icon-log-out"></i>
                            </a>
                        </div>
                        <ul class="pro-body">
                            <li><a href="/profile.html" class="dropdown-item"><i class="feather icon-user"></i>
                                Profile</a></li>
                            <li><a href="{% url 'logout' %}" class="dropdown-item">
                                <i class="feather icon-lock"></i> Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</header>
<!-- [ Header ] end -->

apps/templates/includes/scripts.html
<script src="{{ ASSETS_ROOT }}/js/vendor-all.min.js"></script>
<script src="{{ ASSETS_ROOT }}/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/pcoded.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/dark-mode.js"></script>

apps/templates/includes/sidebar.html
<!-- [ navigation menu ] start -->
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a href="/" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-trending-up"></i>
                </div>
                <span class="b-title">Datta Able</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>Navigation</label>
                </li>
                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                    class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">Dashboard</span></a>
                </li>


                <li class="nav-item pcoded-menu-caption">
                    <label>HR</label>
                </li>
                <li >
                    <a href="{% url 'hr:dahsboard' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">dahsboard</span></a>
                </li>

                <li >
<<<<<<< HEAD
                    <a href="" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">sampleHOME</span></a>
=======
                    <a href="{% url 'studentregister' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">SighnUP Student</span></a>
>>>>>>> master
                </li>

                <li >
                    <a href="{% url 'register' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">Rigester1</span></a>
                </li>

             




                <li class="nav-item pcoded-menu-caption">
                    <label>EXTRA</label>
              
                <li >
                    <a href="{% url 'home:home_old' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">EXTRA Menu</span></a>
                </li>

            </li>



            <li class="nav-item pcoded-menu-caption">
                <label>Library</label>
          
            <li >
                <a href="{% url 'library:library_home' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                        class="pcoded-mtext">Library Home</span></a>
            </li>

        </li>
                
            </ul> 
        </div>
    </div>
</nav>
<!-- [ navigation menu ] end -->