apps/hr/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from .views import *
from apps.home import views


app_name = "hr"
urlpatterns = [

    # The home page
    # path('', views.hrIndex, name='home'),
    path('', dashboard, name='dahsboard'),
    path('allEmp/', EmpView.as_view(), name='emplist'),
    path('teacher/<slug:slug>', TeacherDetailView.as_view(), name='teacher-detail'),
    path('staff/<slug:slug>', StaffDetailView.as_view(), name='staff-detail'),
    path('toooest/', views.index_old, name='st'),
    path('conf/', configView, name='confiHR'),

    # Matches any html file
    #re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    # Auth routes - login / register
    path("", include("apps.authentication.urls")),

    # ADD NEW Routes HERE

    path("hr", include("apps.hr.urls")),
    path("library", include("apps.library.urls")),
    path("admission/", include("apps.admission.urls")),

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls")),

]

apps/hr/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from email.policy import default
from urllib import request
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from apps.authentication.models import *
# from apps.admission import models  # import Subject

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from birthday import BirthdayField, BirthdayManager
from uuid import uuid4
from django.template.defaultfilters import slugify

#
#
GENDER_CHOICES = (
    ('MALE', 'Male'),
    ('FEMALE', 'Female'),
)
BLOOD_CHOICES = (
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
)
STATUS_CHOICES = (
    ('PENDING', 'pending'),
    ('APPROVED', 'approved'),
    ('DENIED', 'denied'),
)


#####
##
#

class Departments(models.Model):
    dep_name = models.CharField(max_length=50)

    def __str__(self):
        return self.dep_name

# العطل الرسمية والاعياد


class DaysOff(models.Model):
    days_name = models.CharField(max_length=50)
    descraption = models.CharField(max_length=500)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.days_name


class LeavesType(models.Model):
    days_name = models.CharField(max_length=50)
    descraption = models.CharField(max_length=500)
    num_of_days = models.IntegerField()
    for_all_genders = models.BooleanField(default=True)
    tot_allowed_days = models.IntegerField()

    def __str__(self):
        return self.days_name


#############################
###############
######
#


class EmpProfile(models.Model):
    slug = models.SlugField(null=True, blank=True)

  #  user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    emp_id = models.IntegerField(null=True, blank=True)
    manager = models.ForeignKey(
        'self', on_delete=models.SET_NULL, null=True, blank=True)
    #
    id_number = models.CharField(max_length=50)
    name = models.CharField(max_length=250)
    address = models.CharField(max_length=400)
    contact_number = models.CharField(max_length=20)
    email = models.EmailField(max_length=254, null=True, blank=True)
    birth_date = BirthdayField()
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    blood_group = models.CharField(max_length=5, choices=BLOOD_CHOICES)
    joining_date = models.DateField()
    position = models.CharField(max_length=100)
    department = models.ForeignKey(
        Departments, on_delete=models.SET_NULL, null=True, blank=True, related_name="employees")
    emp_status = models.CharField(max_length=70)
    salary = models.IntegerField(null=True, blank=True)
    #profile_image = models.ImageField(upload_to='HR/static/HR')
    #contract_upload = models.FileField(upload_to='HR/static/HR')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        queryset = EmpProfile.objects.all()
        if queryset.exists():
            i = EmpProfile.objects.all().count() + 1
            self.emp_id = datetime.datetime.now().strftime(
                "%y") + str("%03d" % i)
        else:
            self.emp_id = datetime.datetime.now().strftime("%y") + "001"

        if not self.slug:
            self.slug = slugify(self.name)

        super(EmpProfile, self).save(*args, **kwargs)


#################################################
####################


class EmpLeaveRequest(models.Model):
    leave_req_id = models.CharField(max_length=15, null=True, blank=True)
    employee = models.ForeignKey(
        EmpProfile, on_delete=models.CASCADE)
    leaveType = models.ForeignKey(
        LeavesType, on_delete=models.CASCADE)
    days_name = models.CharField(max_length=50)
    descraption = models.CharField(max_length=500, null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    num_of_days = models.IntegerField()
    status = models.CharField(
        max_length=35, choices=STATUS_CHOICES, default='pending')
    approved_by = models.CharField(max_length=100, blank=True)

    def save(self, *args, **kwargs):
        queryset = EmpLeaveRequest.objects.all()
        if queryset.exists():
            i = EmpLeaveRequest.objects.all().count() + 1
            self.leave_req_id = datetime.datetime.now().strftime(
                "%y") + str("%04d" % i)
        else:
            self.leave_req_id = datetime.datetime.now().strftime("%y") + "0001"
        super(EmpLeaveRequest, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.employee} {self.leaveType} {self.pk}'


class EmpLeaveRecord(models.Model):
    emp = models.ManyToManyField(EmpProfile,  blank=False)
    leaveTyp = models.ManyToManyField(LeavesType, blank=False)
    tot_days_left = models.IntegerField()

    def __str__(self):
        return f'{self.emp} {self.leaveTyp}'


######################################################################
#####################################
#############


class StaffProfile(EmpProfile):


    user = models.OneToOneField( User, on_delete=models.SET_NULL, null=True, blank=True)
    emp_type = models.CharField(default="staff", max_length=50)


    def __str__(self):
        return self.name

apps/hr/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import Group, Permission
from django.contrib.admin.widgets import FilteredSelectMultiple


class DepartmentsForm(forms.ModelForm):

    class Meta:
        model = Departments
        fields = '__all__'


class DaysOffForm(forms.ModelForm):

    class Meta:
        model = DaysOff
        fields = '__all__'


class LeavesTypeForm(forms.ModelForm):

    class Meta:
        model = LeavesType
        fields = '__all__'

apps/hr/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import template
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import *
from .forms import *
from .filters import *
from apps.admission.models import *
###
from django.http import JsonResponse
from django.shortcuts import render
from django.core import serializers
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
import json


##############


def dashboard(request):
    # using [:4] to limit the query to only showing first 4
    levTy = LeavesType.objects.all()[:4]
    dyff = DaysOff.objects.all()[:4]
    dep = Departments.objects.all()[:4]
    empLeaveRequest = EmpLeaveRequest.objects.all()[:6]
    empProfile = EmpProfile.objects.all()[:6]
    #teacherProfile = TeacherProfile.objects.all()[:6]

    data = {
        "levTy": levTy,
        "dyff": dyff,
        "dep": dep,
        "empLeaveRequest": empLeaveRequest,
        "empProfile": empProfile,
        # "teacherProfile": teacherProfile,

    }
    return render(request, "hr/dahsboard.html", data)


class EmpView(ListView):
    model = EmpProfile
    context_object_name = 'topics'
    paginate_by = 6
    template_name = 'hr/emp_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['filter'] = EmpProfileFilter(
            self.request.GET, queryset=self.get_queryset())
        teachers = TeacherProfile.objects.all()
        stafff = StaffProfile.objects.all()
        context += teachers + stafff
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return EmpProfileFilter(self.request.GET, queryset=queryset).qs


class StaffDetailView(DetailView):

    model = StaffProfile
    template_name = 'hr/staff_profile.html'
    context_object_name = 'staff'

    def get_success_url(self):
        return reverse('detail', kwargs={'slug': self.slug})


class TeacherDetailView(DetailView):

    model = TeacherProfile
    template_name = 'hr/teacher_profile.html'
    context_object_name = 'teacher'

    def get_success_url(self):
        return reverse('detail', kwargs={'slug': self.slug})


def configView(request):

    depForm = DepartmentsForm()
    fDayForm = DaysOffForm()
    leavTyForm = LeavesTypeForm()

    data = {"depForm": depForm, "fDayForm": fDayForm,
            "leavTyForm": leavTyForm, }
    return render(request, "hr/config.html", data)


# def zeroingBalances(request):
 #   holders = CardHolder.objects.all()
  #  print("TTTTTTTTTT")
   # if request.method == "POST":
    #    id_list = request.POST.getlist('boxes')
#
 #       for x in id_list:
  #          CardHolder.objects.filter(pk=int(x)).update(balance=0.00)
   #     messages.warning(
    #        request, ' الصحيحة ')
    #   return render(request, "/")
#
 #   data = {"holders": holders, }
#
 #   return render(request, "main/zeroing_balances.html", data)

apps/templates/hr/EMPLIST.html
{% extends "layouts/base.html" %}

{% block title %} Maps {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div class="pcoded-main-container">
    <div class="pcoded-wrapper">
        <div class="pcoded-content">
            <div class="pcoded-inner-content">
                <!-- [ breadcrumb ] start -->
              
                <!-- [ breadcrumb ] end -->
                <div class="main-body">
                    <div class="page-wrapper">
                        <!-- [ Main Content ] start -->
                        <div class="row">
                            <div class="col-xl">
                                <div >
                                   
                                        <div >
                                             

                                              
                                                    <div class="card ">
                                                      <div class="card-header">
                                                        
                                                        <div class="alert alert-info">
                                                            <span ><h2 style="color:#ffff;font-weight:20px"> الموظفين</h2></span>
                                                 
                                                          </div>
                                            
                                                      <div class="row">
                                                        <div class="col">
                                                          <div class="card card-body" >
                                                      
                                                            <form method="get" >
                                                              {{filter.form }}
                                                            
                                                      
                                                              <button class="btn btn-primary"  type="submit">Search</button>
                                                            </form>
                                                      

                                                            <form action='{% url "hr:create-teacher" %}' method='GET'>
                                                                <button class="btn btn-primary"type='submit'>Adding New Teacher </button>
                                                                </form> 
                                                                         
                                            
                                                          </div>
                                                        </div>
                                                        
                                                      </div>
                                            
                                            
                                            
                                                      <div class="card-body">
                                                        <div class="table-responsive">
                                                          <table class="table tablesorter " id="">
                                                            <thead class=" text-primary">
                                                              <tr>
                                                                <th>
                                                                    Employee Id
                                                                </th>
                                                                <th>
                                                                    Name
                                                                </th>
                                                                <th>
                                                                    Position
                                                                </th>
                                                                <th class="text-center">
                                                                    Department
                                                                </th>
                                                                <th class="text-center">
                                                                    Status
                                                                </th>
                                                         
                                                              </tr>
                                                            </thead>
                                                            <tbody>
                                                                {% for obj in allEMP %}
                                                                                <tr>
                                                                                   
                                                                                    <td >
                                                                                        {{ obj.emp_id }} 
                                                                               
                                                                                    </td>
                                                                                    <td>
                                                                                                {% if obj. %}
                                                                                                          <a href='{% url "hr:staff-detail" obj.slug %}'>{{ obj.name }} </a>
                                                                                                          
                                                                                                48484
                                                                                                {% else %}
                                                                                                <a href='{% url "hr:teacher-detail" obj.slug %}'>{{ obj.name }} </a>
                                                                                                6666666666666666
                                                                                                
                                                                                                {% endif %}
                                                                                    </td>
                                                                                    <td>
                                                                                        {{ obj.position }}
                                                                                    </td>
                                                                                    <td class="text-center">
                                                                                        {{ obj.department }}
                                                                                    </td>
                                                                                    <td class="text-center">
                                                                                        {{ obj.emp_status }}
                                                                                    </td>
                                                                                
                                             
                                                                {% endfor %}
                                                              </tr>
                                                            </tbody>
                                                          </table>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                               
                                            
                                            <!--   Adding pagination     ###################################################-->
                                              <nav aria-label="Page navigation example">
                                                {% if is_paginated %}
                                                <ul class="pagination">
                                                  {% if page_obj.has_previous %}
                                                  <li class="page-item">
                                                    <a class="page-link" href="?page={{page_obj.previous_page_number}}"
                                                      >&laquo;</a
                                                    >
                                                  </li>
                                                  {% else %}
                                                  <li class="page-item disabled">
                                                    <a class="page-link" href="#">&laquo;</a>
                                                  </li>
                                                  {% endif %} 
                                                  {% for i in paginator.page_range %}
                                                   {% if page_obj.number ==  i %}
                                                  <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                                                   {% else %}
                                                  <li class="page-item">
                                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                                  </li>
                                                  {% endif %} {% endfor %} {% if page_obj.has_next %}
                                                  <li class="page-item">
                                                    <a href="?page={{page_obj.next_page_number}}" class="page-link"
                                                      >&raquo;</a
                                                    >
                                                  </li>
                                                  {% else %}
                                                  <li class="page-item disabled">
                                                    <a class="page-link">&raquo;</a>
                                                  </li>
                                                  {% endif %}
                                                </ul>
                                                {% endif %}
                                              </nav>
                                            
                                                   
                                            
                                            

                                         </div>

                                </div>
                            </div>
                        </div>
                        <!-- [ Main Content ] end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!--
<script>
    const data ='{{qs_json}}'
    console.log(data)


    const rdata = JSON.parse(data.replace(/&quot;/g, '"'))
    console.log(rdata)

    const input = document.getElementById('search_here')
    console.log(input)

    let filteredArr = []

    input.addEventListener('keyup',()=>{ 
        box.innerHTML= ""
        filteredArr = rdata.filter(transaction=> transactionId['transactionId'].includes(e.target.value))
        console.log(filteredArr)
        if (filteredArr.length>0){
            filteredArr.map(item=>{
                box.innerHTML +=${transaction['transactionId']}
            })
        }
    })


</script>

-->
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      demo.initGoogleMaps();
    });
  </script>

{% endblock javascripts %}

apps/templates/hr/sample.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">
            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->
                    <div class="page-header">
                        <div class="page-block">
                            <div class="row align-items-center">
                                <div class="col-md-12">
                                    <div class="page-header-title">
                                        <h5 class="m-b-10">Sample Page</h5>
                                    </div>
                                    <ul class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                        <li class="breadcrumb-item"><a href="javascript:">Sample Page</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>HR card</h5>
                                        </div>
                                        <div class="card-block">
                                            <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}